### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by Alabfa** [DinoLeung/TeleDart#198]
Hello,
I had a problem with the [TeleDart Package](https://pub.dev/packages/teledart) from Version 3.0.0 and after,
I Copied exactly the same Example Provided with the package into a project of flutter and whenever I tried to run the app It get me this Error:

> E/flutter ( 6623): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Null check operator used on a null value
> E/flutter ( 6623): #0      main (package:flutter_telegram_bot/main.dart:10:56)
> E/flutter ( 6623): #1      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:129:25)
> E/flutter ( 6623): #2      _rootRun (dart:async/zone.dart:1428:13)
> E/flutter ( 6623): #3      _CustomZone.run (dart:async/zone.dart:1328:19)
> E/flutter ( 6623): #4      _runZoned (dart:async/zone.dart:1863:10)
> E/flutter ( 6623): #5      runZonedGuarded (dart:async/zone.dart:1851:12)
> E/flutter ( 6623): #6      _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:125:5)
> E/flutter ( 6623): #7      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
> E/flutter ( 6623): #8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)

I don't know if this is a Bug or a problem with my project anyhow If anyone got a fix for this problem it would be my pleasure if he replied to me,
Regards

**Comment by Alabfa** [comment]
`final envVars = Platform.environment;` 
this Line was causing that Error I removed it and dealt with a token as String and everything worked just fine
thanks to @sikandernoori for the [clarification](https://github.com/DinoLeung/TeleDart/issues/179#issuecomment-915315692)
