### ISSUE TITLE
Wrong detection of entityType in onMessage()?

### ISSUE THREAD

**Issue by vykend** [DinoLeung/TeleDart#98]
I tried running `TeleDart_example.dart` and when I send any message that was not a registered command (ie. /start), example crashed with this error:

```
Unhandled exception:
NoSuchMethodError: The method 'substring' was called on null.
Receiver: null
Tried calling: substring(1)
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      Event.onMessage.<anonymous closure> (package:teledart/src/teledart/event/event.dart:95:22)
#2      _WhereStream._handleData (dart:async/stream_pipe.dart:203:19)
#3      _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:166:13)
#4      _RootZone.runUnaryGuarded (dart:async/zone.dart:1316:10)
#5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
#6      _DelayedData.perform (dart:async/stream_impl.dart:593:14)
#7      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:709:11)
#8      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:669:7)
#9      _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#10     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#11     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:393:30)
#12     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
#13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```
I've attached screenshot from Telegram app for clarity:
![teledart](https://user-images.githubusercontent.com/9008741/78503968-5c7a9e80-776a-11ea-95df-9b71909cc18f.png)

I don't see any error in `TeleDart_example.dart` so I assume that the error is not on my side.

pubspec.yaml:
```
...
environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  teledart: ^0.0.37
...
```

dart --version:
`Dart VM version: 2.7.2 (Mon Mar 23 22:11:27 2020 +0100) on "windows_x64"`

**Comment by DinoLeung** [comment]
Hotfix has been applied https://github.com/DinoLeung/TeleDart/commit/d7ea90289986ce5735652f662f3f3646cb21df45
